### PR TITLE
API Gateway now working with Consul and Swagger implemented

### PR DESCRIPTION
**Pull request by jbonnett92**
Hi,
Here you can see that Swagger is pulling the documentation from the service:
image

And a working request via Swagger also showing that the API gateway is working:
image

I also added a method to migrate the database, as anyone trying to run the project will have problems with a database not existing. So now it migrates on startup, not the best as multiple services that could be starting multiple instances will cause issues.

### CODE REVIEW

**Comment by madslundt** [comment]
Wow this is really cool.
Thank you for participating!

**Comment by jbonnett92** [comment]
@madslundt Do you have Discord or anything? I'd like to speak to you about some design decisions?

**Comment by madslundt** [comment]
@jbonnett92 Can you send me an email with some of your thoughts? Then I'll see if I can set up a meeting to discuss it.

**Comment by jbonnett92** [comment]
What is your email address?

**Comment by madslundt** [comment]
You can find my email on my github profile page.

**Review by rainbowabul-gif — APPROVED** [review]

**Pull request merged**
